### ISSUE TITLE
KeyError: 'shortName'

### ISSUE THREAD

**Issue by pipivv** [JordiCorbilla/stock-prediction-deep-neural-learning#11]
Hi, this error occurred when I was using the latest version 0.3, how should I solve it, thanks.

tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Ticker: GOOG
Start Date: 2019-08-07
Validation Date: 2019-08-07
Test Run Folder: GOOG_20230202_97122126a51ff4356c4231f245a330d2
Traceback (most recent call last):
  File "stock_prediction_deep_learning.py", line 94, in <module>
    train_LSTM_network(stock_prediction)
  File "stock_prediction_deep_learning.py", line 32, in train_LSTM_network
    plotter = Plotter(True, stock.get_project_folder(), data.get_stock_short_name(), data.get_stock_currency(), stock.get_ticker())
  File "C:\stock-prediction-deep-neural-learning-master_ver0.3\stock_prediction_numpy.py", line 39, in get_stock_short_name
    return self._sec.info['shortName']
KeyError: 'shortName'

**Comment by JordiCorbilla** [comment]
have you tried using the notebook instead?
